templates/dashboard.yaml
templates/elasticsearch.yaml
templates/fluentbit.yaml
templates/kibana.yaml
templates/prometheus.yaml
templates/traefik.yaml

I am starting to identify which are our resource requirements for a certain size of the cluster. However we should specify which is the ideal size for certain default values. Moreover, we could infer these initial values based on the size of the cluster.
related to: https://jira.mesosphere.com/browse/DCOS-53206

 resources: set limits to the resource usage of the addons

---

templates/prometheus.yaml

as shown in the docs: https://grafana.com/docs/installation/configuration/#auto-assign-org-role
I can't find `auto_assign_role`. tested within my kind cluster.

fix grafana role, using wrong key

---

templates/prometheus.yaml

After enabling PSP, saw a failure with on of the pods.
```
Name:               prometheus-kubeaddons-grafana-7bfb99cc8b-bvvdn
Namespace:          kubeaddons
Reason:             AppArmor
Message:            Cannot enforce AppArmor: AppArmor is not enabled on the host
```

grafana: disable AppArmor PSP

---

templates/elasticsearch.yaml

We should consider if we want this disabled by default even when using local storage, or change it to be a configurable value.

elasticsearch: disabled data drain and update strategy

---

templates/opsportal.yaml

uppercase is not valid for Kubernetes names.
tested with my own cluster.

name format error fixes

---

templates/opsportal.yaml

the need to have components separated is required here.

[fix] opsportal deployment component needs to be separated out.

---

templates/prometheus.yaml

Fixes https://jira.mesosphere.com/browse/DCOS-54042
Tested locally, the storage size is the default value:
```
➜  dkphoenix002 k describe pvc -n kubeaddons prometheus-prometheus-kubeaddons-prom-prometheus-db-prometheus-prometheus-kubeaddons-prom-prometheus-0
Name:          prometheus-prometheus-kubeaddons-prom-prometheus-db-prometheus-prometheus-kubeaddons-prom-prometheus-0
Namespace:     kubeaddons
StorageClass:  ebs-csi-driver
Status:        Bound
Volume:        pvc-c6b138a5-7b47-11e9-865c-0aed50195db4
Labels:        app=prometheus
prometheus=prometheus-kubeaddons-prom-prometheus
Annotations:   pv.kubernetes.io/bind-completed: yes
pv.kubernetes.io/bound-by-controller: yes
volume.beta.kubernetes.io/storage-provisioner: ebs.csi.aws.com
volume.kubernetes.io/selected-node: …
```

prometheus: use a PVC instead of an emptyDir

---

templates/elasticsearchexporter.yaml
templates/prometheus.yaml
templates/traefik.yaml

As discussed with Jie, we will add a service monitor that would aim to collect the info from the kubeaddons namespace and for a specific label. Therefore any service exposing a metrics endpoint and with a label `kubeaddons.mesosphere.io/servicemonitor: "true"` should be scrapped.

[prometheus] namespace service monitor

---

templates/calico.yaml

Use the default namespace.
Fixes https://jira.mesosphere.com/browse/DCOS-54029, requires additional changes in `kubeaddons`.

calico: use default namespace

---

templates/traefik.yaml

Increases the number of default traefik pods deployed to help reduce ingress downtime from individual node failures.

Improve Traefik Fault Tolerance

---

templates/velero.yaml

The purpose of this PR is to add Velero, and convert it from the old way we use to deploy it. This PR works to cover the following issues:
* Deal with flakiness in Minio deployments
* Isolate Velero Minio so that's its solely used by Velero
* Add persistent storage to Minio for backups
* Reduce custom logic for Velero, and move remaining logic to extraSteps
* Enable daily cluster-wide backups
* Converts the last few remaining workers so that we can fully deprecate the old style workers (after helm)
At this time its specifically being added using the manifest implementation to better couple together the related minio service and velero quickly and expediently, but [DCOS-54304](https://jira.mesosphere.com/browse/DCOS-54304) was created as a follow up to this to utilize helm and perhaps make …

Add Velero

---

templates/prometheus.yaml

enable etcd metric capture, depends on: https://github.com/mesosphere/mke-lite/pull/251

[DCOS-52112] enabled metrics capturing for etcd assuming a secret exists

---

templates/prometheusadapter.yaml

As an alternative to #20, it has been discussed whether we want to deploy metrics-server with the overlaps that it includes when having prometheus-operator. Therefore there is an alternative https://github.com/DirectXMan12/k8s-prometheus-adapter. That seems to replace metrics-server and is maintained by RH and Google people.

prometheus-adapter: add adapter in replacement of metrics-server

---

templates/prometheusadapter.yaml

1.0.2 has a bug (https://github.com/helm/charts/issues/13716) which
would cause issues with, for instance, `kubectl api-resources`. The bug
was fixed in this PR (https://github.com/helm/charts/pull/14389)
upstream.
Bump the version to 1.0.3 which has the fix.

prometheusadapter: bump the version to 1.0.3

---

templates/awsebscsidriver.yaml

This is similar to what calico daemonset does. If a node is tainted
(e.g., dedicated nodes for some service), we need to make sure csi ebs
driver is still running on that node.

ebscsidriver: made sure it runs on all nodes

---

templates/elasticsearchexporter.yaml

In order to automatically scrape the elasticsearch-exporter service without adding a service monitor, we can use the latest changes

elasticsearch-exporter: add svc labels and rename the service port to metrics

---

templates/prometheus.yaml

Normally, it should be enough increasing it to 50 millicores but we can set it to 100m in prevision of bigger clusters.

alert-manager: increase cpu limit

---

templates/fluentbit.yaml

Add service labels to be discovered by Prometheus and scrape fluent-bit related metrics.

fluentbit: add service labels

---

templates/elasticsearchexporter.yaml

This is a temporal PR to avoid the latest issue regarding yaml formatting.

elasticsearch-exporter: temporally remove the labels

---

templates/awsebscsidriver.yaml

In relation to the changes made here: https://github.com/mesosphere/csi-driver-deployments/pull/5/files, we also need to upgrade the configuration of our ebs-csi-driver settings

awsebscsidriver: upgrade ebs csi configuration

---

templates/prometheus.yaml

This admin API enables the deletion of time series, I am so confident on enabling by default. So it is your call :).

prometheus: enable the admin API by default

---

templates/elasticsearchexporter.yaml
templates/fluentbit.yaml
templates/prometheus.yaml
templates/traefik.yaml

it wasn't pointing to the correct endpoint. 
The endpoint in fluent-bit is different than `/metrics` that is why we have to define the specific path `/api/metrics/prometheus`.

setup fluentbit-prometheus properly

---

templates/dashboard.yaml

Based on the recent MWT, we should increase the memory limits for the dashboard.

dashboard: increase resource limits for memory

---

templates/prometheusadapter.yaml

Fixes https://jira.mesosphere.com/browse/DCOS-54616
Requires https://github.com/helm/charts/pull/14508 to be merged in.
The rule came from https://github.com/DirectXMan12/k8s-prometheus-adapter/blob/master/deploy/manifests/custom-metrics-config-map.yaml#L73
Tested with https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/.

prometheus-adapter: add resourceRules to fix HPA and kubectl top

---

templates/velero.yaml

The purpose of this task is to separate the Velero batch job from the lists so that it can be identified and operated on separately from the list items.

Separate Velero batch job

---

templates/awsebscsidriver.yaml
templates/calico.yaml

* New release from https://docs.projectcalico.org/v3.6/release-notes/
* Match [upstream version](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/deploy/kubernetes/manifest.yaml#L333)

bump addons versions

---

templates/prometheus.yaml

By setting the name, the auto-generated name via the prometheus-operator will result in `db-prometheus-prometheus-kubeaddons-prom-prometheus-0` which contains 53chars.
```
E0625 04:15:15.056075       1 volume.go:128] Internal Server Error: failed to create volume 'pvc-d480ba57-96ff-11e9-9cea-0a44df461fe2': response: Service "pvc-d480ba57-96ff-11e9-9cea-0a44df461fe2-ctrl-svc" is invalid: metadata.labels: Invalid value: "prometheus-prometheus-kubeaddons-prom-prometheus-db-prometheus-prometheus-kubeaddons-prom-prometheus-0": must be no more than 63 characters
```
```
db-prometheus-prometheus-kubeaddons-prom-prometheus-0   Bound    pvc-66873662-30d8-4f1d-a9f9-c7863b97d7b3   50Gi       RWO            ebs-csi-driver   3m3s
```

prometheus: specify a volume name

---

helm/localvolumeprovisioner/templates/deployment.yaml
helm/localvolumeprovisioner/templates/service.yaml

Add a service to collect all the metrics from the localvolumeprovisioner, so it can be scrapped by our default service monitor.

localvolumeprovisioner: add changes to scrape the metrics endpoint

---

templates/localvolumeprovisioner.yaml

This PR bumps the localvolumeprovisioner chart version from v0.1.0 to v0.1.1.
It also changes the chart name to not include the name of the helm chart repository (which is implicitly set to the FQDN of the `repo:` field value.) 
Requires:

templates/localvolumeprovisioner: bump chart version to 0.1.1

---

templates/awsebscsiprovisioner.yaml
templates/awsebsprovisioner.yaml
templates/localpathprovisioner.yaml

This PR consolidates the storage addons around the pattern that was pioneered by the localvolumeprovisioner addon:
- Instead of using a manifest, an addon now points to a helm chart in the mesosphere/charts repository.
- Instead of having separate addons for storage provisioners and storage classes, we only have addons for storage provisioners.
- Each addon defines an associated storage class. 
- Each addon supports the `storageclassdefault: true|false` configuration option. This option controls whether or not the associated storage class will be marked as the default storage class for the cluster.
- The name of the associated storage class matches the name of the addon.
The following addons were renamed or removed in the process:
- aws{storageclass,storageclassdefault} -> …

Port storage addons to charts repo from kubeaddons-config

---

templates/dex-k8s-authenticator.yaml

A new version of the chart that deploys authenticator version that does not expose OAuth client secret to the authenticated user.
To override HTML templates in the official container this PR introduces new `ConfigMap` that injects custom version of HTML templates into the authenticator container.
JIRA: https://jira.mesosphere.com/browse/DCOS-56105
Chart PR: https://github.com/mesosphere/charts/pull/24

templates/dex-k8s-authenticator: bump to hide oidc client secret from users

---

templates/kommander.yaml

the available version is 0.1.0 https://github.com/mesosphere/charts/tree/master/docs/stable

kommander: use available version

---

templates/dex.yaml

Bump dex container to include new mesosphere theme.
JIRA: https://jira.mesosphere.com/browse/DCOS-56022
The theme was merged in https://github.com/mesosphere/dex/pull/1

templates/dex: bump dex to include new theme

---

templates/traefik-forward-auth.yaml

Change the `traefik-forward-auth` rules to authenticate only the `/ops/portal` path, and allow all other paths.  This uses the `traefik-forward-auth` rules to do this.
Later, we plan to get `ingress` rules to handle this for us.

Change rules to authenticate only Ops Portal

---

templates/kommander.yaml

```
Error: error installing: error generating workflow from Addon list: failed to create workflow for https://github.com/mesosphere/kubeaddons-configs@hectorj2f/ingress-annotations: failed to deploy addon CRD kommander; error: deployConfig failed: exit status 1 [stderr: The Addon "kommander" is invalid:
* metadata.annotations: Invalid value: "endpoint.kubeaddons.mesosphere.io/": name part must be non-empty
* metadata.annotations: Invalid value: "endpoint.kubeaddons.mesosphere.io/": name part must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]')
]
```

kommander: fix wrong annotation endpoint

---

templates/traefik-forward-auth.yaml

Use a specific tag for the `traefik-forward-auth` image. This provides some stability before moving the image to the `mesosphere` repo.

Use a specific image for traefik-forward-auth

---

templates/prometheus.yaml

This is the header that traefik auth forwarder is using.
https://github.com/thomseddon/traefik-forward-auth#forwarded-headers

grafana: use X-Forwarded-User for the auth header

---

templates/localpathprovisioner.yaml
templates/localvolumeprovisioner.yaml
templates/prometheusadapter.yaml
templates/velero.yaml

fixed velero so that is
- enabled in aws
- enabled in none
- not and addon in docker type.
fixed localpath and volume provisioners
- removed from aws deployment
prometheusadapter
- should reflect options found in prometheus

fixes cloudProvider values found in specs

---

templates/traefik.yaml

Hi there, 
while reviewing your product, I stumbled across 2 minors thing in the Traefik's default manifest:
* The link to the documentation should point explicitly to the current stable `v1.7`, to avoid breaking when the brand new Traefik v2.0 will be released.
* There was a duplicated YAML stanza about prometheus metrics enablement.
Thanks for your work!

Minor changes on Traefik's manifest

---

templates/traefik-forward-auth.yaml

We should use a separate rule name for the landing page.

traefik-forward-auth: fix a bug in rules

---

templates/localvolumeprovisioner.yaml

This is needed for AWS tests, but also a user on AWS might want to enable this.
@alejandroEsc what happens if both csi and this is enabled? Will the correct SC be set?

localvolumeprovisioner: allow for aws

---

templates/traefik-forward-auth.yaml
templates/traefik.yaml

This PR removes authentication so that integration of the new konvoy-ui can get done.

Prepare to replace traefik forward auth with ingress annotations

---

dashboards/localvolumeusage.yaml

This dashboards shows the volume data usage of persistent volume claims.
These claims can be filtered by storage class and instance.
JIRA: [DCOS-55516](https://jira.mesosphere.com/browse/DCOS-55516)

dashboards: add a dashboard to display per-node volume space usage

---

templates/localvolumeprovisioner.yaml

all other storage classes uses the same label, this should bring us to consistency.

storage class label fixed

---

templates/kibana.yaml

Fails with below since `v0.0.1-alpha` doesn't support kibana or those envs
```
2019/07/20 01:46:22 can't yet reach kibana: Get http://kibana.kibana:5601: dial tcp: lookup kibana.kibana on 10.0.0.10:53: no such host
2019/07/20 01:46:22 waiting for kibana to be responsive
```
After updating the pod came up:
```
kibana-kubeaddons-588cc57fc4-84m26                                2/2     Running   3          16m
```

kibana: bump sidecar version to support envs

---

templates/traefik-forward-auth.yaml

Now that ingress annotations determine which parts of the site require authentication
we no longer need rules in traefik-forward-auth.
Also, change to use image from Mesosphere Docker Hub.

Remove redundant rules

---

templates/kommander.yaml
templates/konvoy-ui.yaml
templates/prometheus.yaml

Bump Kommander to the latest version which exports metrics, and add the kommander namespace to the Prometheus service monitor match configs to get the metric endpoints scraped.

Export kommander metrics to Prometheus

---

templates/opsportal.yaml

related to: https://github.com/mesosphere/charts/pull/67
This PR adds the logo to the ops/landing page

opsportal: bump chart version

---

templates/kommander.yaml

Use the new version with reduced default CPU request.
xref: https://github.com/mesosphere/charts/pull/83

kommander: bump chart version

---

templates/dex-k8s-authenticator.yaml

I still don't know when we are going to be tagging images, but this was the tag I tested with.
Built from https://github.com/mesosphere/kubeaddons-extrasteps/pull/7

dex-k8s-authenticator: add missing ConfigMap value

---

templates/localvolumeprovisioner.yaml

This is a proposal to overcome this issue https://github.com/kubernetes/kubernetes/issues/76308 when using priorityClassName: https://github.com/mesosphere/charts/blob/dev/stable/localvolumeprovisioner/values.yaml#L12
My intention is to treat the localvolumeprovisioner similarly to how it is treated another storage provisioner

localvolumeprovisioner: change the namespace to kube-system

---

templates/prometheus.yaml

Bump prometheus-operator chart version to 5.10.4. This bump includes: new Konvoy UI dashboard, a bug fix to get ES dashboard installed successfully, and typo fix in the mesosphere resources.

Bump prometheus-operator chart to 5.10.4

---

templates/prometheus.yaml

Contains updates from https://github.com/mesosphere/charts/pull/100

Bump prometheus-operator to 5.10.6

---

templates/prometheus.yaml
templates/velero.yaml

Adds service labels to velero to get its metrics scraped by prometheus. Depends on https://github.com/mesosphere/charts/pull/104

Scrape velero monitoring prom endpoint

---

templates/prometheusadapter.yaml

related to: https://jira.mesosphere.com/browse/DCOS-56671

[DCOS-56671] prometheus-adapter: set resources

---

templates/kibana.yaml
templates/prometheus.yaml

Adds the [kibana-prometheus-exporter](https://github.com/pjhampton/kibana-prometheus-exporter) plugin to kibana which exports metrics in prometheus format to `/_prometheus/metrics`, and adds the necessary service labels to get the metrics scraped by prometheus.

Export and scrape Kibana metrics

---

templates/prometheus.yaml

Bump prometheus-operator to 5.10.9 to pull in new Kibana dashboard.

Bump prometheus-operator to 5.10.9

---

templates/dex-k8s-authenticator.yaml

The dependency setup for this Addon is currently broken. It intends to depend on two different addons, but currently the functionality is that it's depending on one Addon with two unrelated provisions. Dex already depends on the ingress controller, so we can remove that dependency at this level to simplify dependency management for this Addon.

[bug] Remove ingress controller dep from dex-k8s-auth

---

templates/prometheusadapter.yaml

The query was indeed returning an empty result because we were replacing a valid label name `node` by `instance` that it didn't exist
```
kubectl get --raw "/apis/metrics.k8s.io/v1beta1/nodes"  --kubeconfig=admin.conf
{"kind":"NodeMetricsList","apiVersion":"metrics.k8s.io/v1beta1","metadata":{"selfLink":"/apis/metrics.k8s.io/v1beta1/nodes"},"items":[{"metadata":{"name":"ip-10-0-193-120.us-west-2.compute.internal","selfLink":"/apis/metrics.k8s.io/v1beta1/nodes/ip-10-0-193-120.us-west-2.compute.internal","creationTimestamp":"2019-09-02T12:31:07Z"},"timestamp":"2019-09-02T12:31:07Z","window":"1m0s","usage":{"cpu":"208m","memory":"2263684Ki"}},{"metadata":{"name":"ip-10-0-194-69.us-west-2.compute.internal","selfLink":"/apis/metrics.k8s.io/v1beta1/nodes/ip-10-0-194-69.us-west-2.compute.internal …
```

prometheusadapter: fix empty node metrics

---

templates/prometheus.yaml

```
> {job="kubernetes-keepalived"}
scrape_duration_seconds{endpoint="snmp-metrics",instance="172.17.0.3:6161",job="kubernetes-keepalived",namespace="kube-system",node="out-darwin-control-plane-0",pod="keepalived-out-darwin-control-plane-0"}	0.071160588
scrape_samples_post_metric_relabeling{endpoint="snmp-metrics",instance="172.17.0.3:6161",job="kubernetes-keepalived",namespace="kube-system",node="out-darwin-control-plane-0",pod="keepalived-out-darwin-control-plane-0"}	24
scrape_samples_scraped{endpoint="snmp-metrics",instance="172.17.0.3:6161",job="kubernetes-keepalived",namespace="kube-system",node="out-darwin-control-plane-0",pod="keepalived-out-darwin-control-plane-0"}	24
snmp_scrape_duration_seconds{endpoint="snmp-metrics",instance="172.17.0.3:6161",job="kubernetes-keepalived",namespa …
```

Expose keepalived metrics

---

templates/prometheus.yaml

In preparation for running [Karma](https://github.com/helm/charts/tree/master/stable/karma) as a central alerting dashboard in Kommander, we need to bump Konvoy Alertmanagers up to a version > 0.16.x in order to be compatible with Karma (it is currently defaulted to v0.16.2 on our version of prometheus-operator). See https://github.com/prymitive/karma/issues/115 for more details

Bump alertmanager version to v0.17.0

---

templates/prometheus.yaml

Enables the Thanos sidecars on prometheus-operator. This is in preparation for a Thanos Querier running in Kommander that will collect all Prometheus metrics through the sidecar on all the Konvoy clusters it is connected to. In the future, we will likely also utilize the sidecars for storage backups.
It looks like we are on v0.29.0 of prometheus-operator, unless I'm mistaken (referencing https://github.com/mesosphere/charts/blob/dev/staging/prometheus-operator/Chart.yaml#L2). I've fixed the label to reflect the correct version here as well. Thanos >0.4 is incompatible with prometheus-operator versions older than 0.31 (see https://github.com/coreos/prometheus-operator/issues/2635), which is why I've set the Thanos version to 0.4. If we upgrade prometheus-operator to >=0.31, we'll be able …

Enable Thanos sidecar

---

templates/awsebscsiprovisioner.yaml

Fixes `failed to create VolumeSnapshotResource:` error and adds support for passing `env` vars.

awsebscsiprovisioner: bump to 0.3.1

---

templates/kommander.yaml
templates/opsportal.yaml

so that opsportal does not deploy kubefed

[fix] update kommander and opsportal charts 

---

templates/dex.yaml
templates/traefik-forward-auth.yaml
templates/traefik.yaml

We need to include cert-manager in the dependencies of dex, so it gets installed before.

dex: requires cert-manager

---

templates/dex.yaml
templates/traefik-forward-auth.yaml
templates/traefik.yaml

Cherry-pick for 1.15.4 release branch
We should re-tag stable-1.15.4-2 release from this branch. The existing tag include an addon that we soon removed (kube-oidc-proxy) on master branch.
Also, kommander was bumped in master, which is not intended for 1.15.4-x releases. Otherwise, the link to /ops/portal/kommander will return `Cannot GET /kommander`.

Cherry-pick for 1.15.4 branch

---

templates/traefik-forward-auth.yaml

- remove additional slash from redirect URI
- redirect clients to specific host to ensure correct cookies
See https://github.com/mesosphere/konvoy/pull/845 for tests

Update to traefik-forward-auth 1.0.4

---

templates/dex.yaml

Bump the dex chart version to 1.6.4. This includes the dex-controller
subchart for declarative management.
I tested the upgrade from the stable-1.15.4-2 to this version.

dex: bump to version 1.6.4

---

templates/nvidia.yaml

This addon includes nvidia drive container and device plugin.
Corresponding to https://github.com/mesosphere/charts/pull/120

nvidia: Added nvidia kubeaddon config

---

templates/cert-manager.yaml

The new version fixes the upgrade issue due to hook resources.

cert-manager: bump to 0.1.5

---

templates/velero.yaml

Bringing in the changes from https://github.com/mesosphere/kubeaddons-configs/pull/241, adding ability to pass annotations to the dex service and create an internal ELB.

velero: bump version to support minio service annotations

---

templates/kube-oidc-proxy.yaml

deps: https://github.com/mesosphere/charts/pull/172

Bump kube-oidc-proxy chart version

---

templates/prometheus.yaml

The new Prometheus Alerts UI design isn't ideal:
The UI enhancement was released in Prometheus v2.10.0 -- let's use Prometheus v2.9.2 instead (it is defaulted to v2.10.0 in the helm chart), and upgrade once that design is improved (there is a [PR open](https://github.com/prometheus/prometheus/issues/5655) that looks like it'll improve the UI). I've also updated the labels to correctly reflect the versions of each component in prometheus-operator.
UI using v2.9.2:

Use Prometheus v2.9.2

---

templates/dex.yaml

Bump to use dex-controller v0.2.0 that supports static clients.

dex: bump to use dex-controller v0.2.0

---

templates/gatekeeper.yaml

Re-enable it after we merged a PR that fixes the issues it brought.

gatekeeper: enable it by default

---

templates/awsebscsiprovisioner.yaml
templates/awsebsprovisioner.yaml
templates/defaultstorageclass.yaml
templates/localvolumeprovisioner.yaml

there has been a discussion about how to handle cases where there are 2 default storage classes, as that can create errors for other addons down the road.
part of this solution is having a validating webhook that checks for whether 2 default storage classes installed, see kep: https://github.com/mesosphere/kubeaddons/blob/master/keps/20190903-defaultstorageclass-validating-webhook.md
this is implemented in: https://github.com/mesosphere/charts/pull/124
to protect users from having multiple default storageclasses, all storageclass addons now have this addon as a requirement. as written in the PR.

default storage class addon and requirements

---

templates/kube-oidc-proxy.yaml

This PR adds `goupsPrefix` parameter. This is a fix for regression when we've switched from configuring `kube-apiserver` with `kube-oidc-proxy`.
Successful docker build:
https://github.com/mesosphere/konvoy/pull/908
https://teamcity.mesosphere.io/viewLog.html?buildId=2361673&buildTypeId=ClosedSource_Konvoy_KonvoyE2eDocker

kube-oidc-proxy: add groupsPrefix

---

templates/prometheus.yaml

This adds a port to the Prometheus service that exposes the Thanos sidecar's gRPC. I tested this by deploying Konvoy with this config and observing that `kubectl -n kubeaddons describe service prometheus-kubeaddons-prom-prometheus` shows the added gRPC port.
This gRPC service will be used by Thanos Querier, running as part of Kommander. Querier will be added in a separate PR.
https://jira.mesosphere.com/browse/DCOS-59074

Add service port for Thanos gRPC

---

CONTRIBUTING.md
templates/awsebscsiprovisioner.yaml
templates/awsebsprovisioner.yaml
templates/cert-manager.yaml
templates/dashboard.yaml
templates/defaultstorageclass.yaml
templates/dex-k8s-authenticator.yaml
templates/dex.yaml
templates/elasticsearch.yaml
templates/elasticsearchexporter.yaml
templates/fluentbit.yaml
templates/gatekeeper.yaml
templates/kibana.yaml
templates/kommander.yaml
templates/konvoyconfig.yaml
templates/kube-oidc-proxy.yaml
templates/localvolumeprovisioner.yaml
templates/metallb.yaml
templates/nvidia.yaml
templates/opsportal.yaml
templates/prometheus.yaml
templates/prometheusadapter.yaml
templates/traefik-forward-auth.yaml
templates/traefik.yaml
templates/velero.yaml

This PR adds annotations intended to help the [Kubeaddons Catalog](https://github.com/kubeaddons/) track revisions to Addons. These are required for this repo to be compliant with the Catalog currently, with hopes of not needing them later.

Add Catalog annotations to addons

---

templates/dashboard.yaml
templates/prometheus.yaml

Cherrypick of https://github.com/mesosphere/konvoy/pull/923 to previous branch.
Containerd mirror feature can not pull k8s.gcr.io images https://github.com/containerd/containerd/issues/3756

dashboard/prometheus: use gcr.io/google_containers instead of k8s.gcr.io

---

templates/dex-k8s-authenticator.yaml

This include the fix to the SIGTERM issue
https://github.com/mesosphere/dex-k8s-authenticator/pull/1

dex-k8s-authenticator: bump to 1.1.9

---

templates/kibana.yaml
templates/prometheus.yaml

Please see https://github.com/mesosphere/kubeaddons-extrasteps/pull/22 for a full description of this work. The extrasteps functionality is pulled into a prometheus container - ideally this would be an initContainer, but that feature was introduced in a later version of prometheus-operator ([0.32.0](https://github.com/coreos/prometheus-operator/releases/tag/v0.32.0), or helm chart versions >=6.8.0; we are on 5.19). When we eventually upgrade to a high enough version, we should move this into an initContainer. Until it is moved to an initContainer, there will be some errors (pasted below) in the reload and thanos sidecar containers until the configmap is written out and the env variable is defined, but it's pretty quick.
When the corresponding extrasteps and chart PRs are merged in, I'll …

prometheus: Set externalLabels cluster label to kube-system ns uid

---

templates/dex-k8s-authenticator.yaml
templates/dex.yaml
templates/kube-oidc-proxy.yaml
templates/reloader.yaml
templates/traefik-forward-auth.yaml
templates/traefik.yaml

This PR adds new https://github.com/stakater/Reloader addon.
`Reloader` allows to explicitly set rules on which deployments will get a rolling update in a case when a config map or a secret contents get updated.
The proposed annotations configure `Traefik` to reload on `konvoconfig-kubeaddons` update and certificate change. When a user sets a new `clusterHostname` domain this will trigger the first reload of traefik. The init-container will update certificate specification and adds new domain. The `cert-manager` will pick up the change and it will re-issue the certificate. The secret that holds the certificate gets updated and that will trigger the second Traefik reload.
Other components are only reloaded when traefik certificate changes.
This PR also bumps multiple charts that will use …

reloader: add new addon

---

templates/prometheus.yaml

Upgrading our version of Thanos for the sidecar to v0.8.1 - tested this version with no issues. The Thanos helm chart we will be using (for Querier) is on v0.8.1 so I wanted to bring our version in line with that chart.
I've also added a service monitor endpoint to get the (future, currently in review) Thanos Querier metrics scraped. Since Kommander doesn't have its own Prometheus, we need to pull in these metrics via the "Konvoy Prometheus". If we do ever add a separate Prometheus to Kommander, we can remove this endpoint (and add it to the Kommander Prometheus config instead). The good news is that there are no issues if the specified endpoints/targets don't exist (see images). Once these metrics are scraped, we can add dashboards for Thanos Querier metrics to Kommander's Grafana.

[prometheus] Upgrade thanos sidecar, scrape thanos query metrics

---

templates/kibana.yaml
templates/prometheus.yaml

To be able to support running Grafana and Kibana addons running in air-gapped environments we needed to stop downloading the plugins at startup and instead provided sidecar containers in the pod where Grafana and Kibana can used a shared volume to get the plugins.
https://github.com/mesosphere/kubeaddons-sidecars
Tested by deploying in a cluster with no internet access, before these pods would require an HTTP_PROXY env vars set.
```
➜  dkkonvoyendpoints k exec -it -n kubeaddons kibana-kubeaddons-775d7df947-sj9ht -c kibana bash
bash-4.2$ ls -la /usr/share/kibana/plugins/
total 0
drwxr-xr-x. 3 root   root  40 Oct 29 18:52 .
drwxrwsr-x. 1 kibana root  34 Mar 21  2019 ..
drwxr-sr-x. 5 kibana root 115 Oct 29 18:52 kibana-prometheus-exporter
bash-4.2$ curl -m 3 google.com
curl: (7) Failed to …
```

grafana/kibana: use a sidecar container for plugins

---

templates/dex-k8s-authenticator.yaml
templates/dex.yaml

Testing in https://github.com/mesosphere/konvoy/pull/964

dex-k8s-authenticator: bump versions for distributed auth

---

templates/kube-oidc-proxy.yaml

Otherwise, the group based RBAC won't work because the proxy does not
know which claim from the JWT token to look for.
Tested manually using the following test LDAP server
https://github.com/mesosphere/dex-controller/blob/master/config/samples/ldap_connector.yaml
https://github.com/mesosphere/dex-controller/blob/master/config/samples/ldap_password.yaml
Also this CRB:
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
name: scientists-admin
roleRef:
apiGroup: rbac.authorization.k8s.io
kind: ClusterRole
name: cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
kind: Group
name: oidc:scientists
```
And login using:
```
username: tesla
password: password
```

kube-oidc-proxy: add the missing group claim

---

templates/dex-k8s-authenticator.yaml

Automatically reload `dex-k8s-authenticator` on its config map change.
This is necessary when DKA controller adds new managed cluster to the config map.

dex-k8s-authenticator: reload pod on config change

---

templates/nvidia.yaml

Bump the Nvidia helm chart to 0.1.2, which includes the image update for nvidia driver and nvidia device plugin.
Add the default nvidia driver image tag for centos, which make it configurable in Konvoy cluster.yaml.

Bump Nvidia chart version and make nvidia driver image tag configurable.

---

templates/kommander.yaml

This will pull in the grafana dashboard for Thanos Query metrics on Kommander. Blocked on https://github.com/mesosphere/charts/pull/231, once that is merged, this is good to go.

kommander: update chart version to 0.1.53

---

templates/traefik-forward-auth.yaml

For identical roles, a priority annotation must exist on all ingress definitions in order to override the ingress definition with another.

Add priority to ingress

---

templates/dex.yaml

This version fixes a bug causing dex static clients to be overwritten

Bump kubeaddons-addon-initializer for dex

---

templates/kommander.yaml

This bumps kommander to pull in https://github.com/mesosphere/charts/pull/235.

Bump kommander

---

templates/traefik-forward-auth.yaml

This backports the following fix to stable/1.15.5 branch.
https://github.com/mesosphere/charts/pull/135

tfa: backport the whitelist/domain bug

---

templates/kommander.yaml

This bumps kommander and adds configuration that directs the reloader addon to restart kommander's karma deployment if its configmap is edited.
I tested this by deploying a Konvoy cluster using this branch's addons, and then adding an alertmanager entry to karma's configmap. This caused karma to be redeployed, and the new pod's logs mentioned the added alertmanager.

kommander: Reload karma configmap on edit

---

templates/kudo.yaml

Once the https://github.com/mesosphere/charts/pull/257 is merged we need to update the KUDO addon to use the version `0.8.0` of the KUDO

bump kudo chart to 0.1.2

---

templates/istio.yaml

- Adding `appversion` & `docs` annotations for both `kiali` & `jaegar` so that their UI service cards will display the correct version and docs links.

feat(istio): add version & docs for istio UI cards

---

templates/localvolumeprovisioner.yaml

It seems this got merged but there was a wrong property set here: https://github.com/mesosphere/kubeaddons-configs/commit/0a5057a1f3dc7603ea3d40386fea88f149caa8d9#diff-940268ba9fc726ba58c83765edbbbf52

templates: fix docker for the local volume provisioner

---

templates/external-dns.yaml

By default, external-dns watches service and ingress objects for external DNS configuration. This PR enables that default setting

enable default setting for service in external-dns

---

templates/kommander.yaml

Bumps kommander to 0.2.12 to pull in the dashboard for multi-cluster view of cpu/mem

kommander: version bump

---

templates/kommander.yaml
templates/opsportal.yaml

CI is broken in Konvoy at this moment. Both AWS and Docker builds are broken with the following error:
https://teamcity.mesosphere.io/viewLog.html?buildId=2447341&buildTypeId=ClosedSource_Konvoy_KonvoyE2eDocker&tab=buildLog&_focus=6659
all builds are red https://teamcity.mesosphere.io/viewLog.html?buildId=2447341&buildTypeId=ClosedSource_Konvoy_KonvoyE2eDocker

Revert "chore: bump kommander/opsportal charts for new image tag 1.150.5"

---

templates/kommander.yaml

Necessary until we do proper tagging in kubeaddons-configs.

chore(kommander): Upgrade kubeaddons-configs mapping to kommander-beta6

---

templates/dashboard.yaml
templates/dispatch.yaml
templates/elasticsearch.yaml
templates/elasticsearchexporter.yaml
templates/fluentbit.yaml
templates/kibana.yaml
templates/metallb.yaml
templates/prometheus.yaml
templates/velero.yaml

Blocked by https://github.com/mesosphere/charts/pull/283
Bumped all the upstream chart versions to support Kubernetes v1.16 apis.
Ran Konvoy and the tests passed, https://github.com/mesosphere/konvoy/pull/1025 (the one failure was unrelated).
This includes an test where we upgrade from Konvoy v1.1.x release to the release and all the addons got upgraded successfully. 
Tested a bunch of times manually also.

chore: bump addons versions to support Kubernetes v1.16

---

templates/kommander.yaml

Bump kommander to pull in kommander's prometheus datasource to populate the thanos querier dashboard, see: https://github.com/mesosphere/charts/pull/279

kommander: Bump to v0.2.19

---

templates/kommander.yaml

Cherrypicked to kommander-beta7 branch.

chore: bump kommander chart to 0.2.26

---

templates/traefik-forward-auth.yaml

legacy patch for tfa, also https://github.com/mesosphere/kubernetes-base-addons/pull/13 for konvoy 1.3+

bump tfa to 1.0.6

---

templates/dashboard.yaml

This is needed to support upgrading now that dashboard has migrated to the kubeaddons namespace

apply upgrade strategy

---

templates/kommander.yaml

Blocked by https://github.com/mesosphere/charts/pull/318 - once that is merged, I will modify the chart repo to point back to `mesosphere`.
See the Testing section in https://github.com/mesosphere/charts/pull/318#issue-354269295

kommander: bump chart to 0.2.29
