templates/dashboard.yaml

As requested by Jie in https://mesosphere.slack.com/archives/CGZAKQNHJ/p1557354793361000

dashboard: increase cpu limits

---

templates/traefik.yaml

Discussed in https://mesosphere.slack.com/archives/CGZAKQNHJ/p1557357468369400?thread_ts=1557356874.366800&cid=CGZAKQNHJ

traefik: increase the cpu limits

---

crds/kubeaddons_v1alpha1_addon.yaml
templates/dashboard.yaml
templates/elasticsearch.yaml
templates/fluentbit.yaml
templates/kibana.yaml
templates/metallb.yaml
templates/prometheus.yaml
templates/traefik.yaml

Fixes https://jira.mesosphere.com/browse/DCOS-53706
Added a new filed in the CRD `version` and then just grabbed the latest versions for the charts we are using.

helm: pin chart versions

---

templates/elasticsearchexporter.yaml

Add exporter for elasticsearch

elasticsearch: add exporter for prometheus

---

templates/elasticsearch.yaml

We are checking if these new settings would tackle recent issues on soak

elasticsearch: increase settings

---

templates/velero.yaml

This PR adds Velero to the manifest based addons.

Add Velero

---

templates/prometheus.yaml

we've been seeing CPUThrottlingHigh errors in the
prometheus dashboard

bump prometheus resource usage

---

templates/elasticsearchexporter.yaml

Reverts mesosphere/kubeaddons-configs#43

Revert "elasticsearch-exporter: temporally remove the labels"

---

templates/elasticsearchexporter.yaml

I am waiting for the upstream PR to be merged first :/

elasticsearch-exporter: upgrade version due to a bugfix

---

templates/prometheus.yaml

bump up grafana cpu

---

prometheus-rules/etcd-rules.yaml

adding our ow rules to prometheus, here we remove the false positive alerts.

prometheus rules for etcd

---

templates/velero.yaml

This PR exposes the Velero Minio instance via service LB.

Add Velero minio LB

---

templates/prometheus.yaml

prometheus: specify an additional scrape to collect containerd metrics

---

templates/traefik.yaml

Please see https://jira.mesosphere.com/browse/DCOS-55916 for detail

enables ingress status update by Traefik

---

templates/localvolumeprovisioner.yaml

JIRA: [DCOS-55514](https://jira.mesosphere.com/browse/DCOS-55514)

Add a template for the local volume provisioner

---

templates/dex-k8s-authenticator.yaml
templates/dex.yaml

Rename `/dex-k8s-authenaticator` endpoint to `/token`.
JIRA: https://jira.mesosphere.com/browse/DCOS-56106

templates/dex: rename /dex-k8s-authenticator to /token endpoint

---

templates/kommander.yaml

kommander: be a chart

---

templates/awsebscsidriver.yaml
templates/awsebscsiprovisioner.yaml
templates/calico.yaml
templates/dashboard.yaml
templates/dex-k8s-authenticator.yaml
templates/dex.yaml
templates/elasticsearch.yaml
templates/elasticsearchexporter.yaml
templates/fluentbit.yaml
templates/kibana.yaml
templates/kommander.yaml
templates/localpathprovisioner.yaml
templates/metallb.yaml
templates/opsportal.yaml
templates/prometheus.yaml
templates/prometheusadapter.yaml
templates/traefik.yaml

Adding annotations to unblock kommander ui

kommander required annotations

---

dashboards/localvolumeprovisioner.yaml

* Show average durations instead of heatmaps
* Add dashboards for deletions
* Distinguish between request types

dashboards: update localvolumeprovisioner dashboard

---

templates/dex.yaml
templates/opsportal.yaml
templates/traefik-forward-auth.yaml
templates/traefik.yaml

Configuration for the traefik-forward-auth authorizer, providing Ops Portal authentication and authorization.

Ops Portal authentication and authorization

---

templates/awsebscsiprovisioner.yaml
templates/awsebsprovisioner.yaml
templates/kommander.yaml
templates/localvolumeprovisioner.yaml

updating chart values with whats found in mesosphere/charts

updated chart versions consistent with charts repo

---

templates/awsebscsiprovisioner.yaml
templates/awsebsprovisioner.yaml
templates/kommander.yaml

- updated chart versions to latest
- set awsebsprovisioner.yaml as disabled

updated chart versions and updated awsebsprovisioner

---

templates/kommander.yaml

Once we upgrade kommnader, we should bump the version here

kommander: bump chart version

---

templates/dex.yaml

JIRA: https://jira.mesosphere.com/browse/DCOS-56390
**Depends on**
* https://github.com/kubeaddons/extrasteps/pull/15 and new container release
* https://github.com/mesosphere/charts/pull/40
**Enables**
* https://github.com/mesosphere/kubeaddons/pull/310

templates/dex: add initcontainer configuration

---

templates/kommander.yaml
templates/traefik-forward-auth.yaml

No auth needed for the landing page.

traefik-forward-auth: allow access to landing page

---

templates/konvoy-ui.yaml
templates/opsportal.yaml

depends on https://github.com/mesosphere/charts/pull/52.
also should fix annotations, once we get the docker image tag.

add konvoy-ui and opsportal config

---

templates/awsebscsiprovisioner.yaml
templates/awsebsprovisioner.yaml
templates/dashboard.yaml
templates/dex-k8s-authenticator.yaml
templates/dex.yaml
templates/elasticsearch.yaml
templates/elasticsearchexporter.yaml
templates/fluentbit.yaml
templates/kibana.yaml
templates/localpathprovisioner.yaml
templates/localvolumeprovisioner.yaml
templates/metallb.yaml
templates/prometheus.yaml
templates/prometheusadapter.yaml
templates/traefik-forward-auth.yaml
templates/traefik.yaml
templates/velero.yaml

Fix the minimum supporter versions to point to v1.15.0

templates: fix min supported version

---

templates/konvoy-ui.yaml

related to: https://github.com/mesosphere/charts/pull/53

konvoy-ui: don't attempt to create the CRD

---

templates/konvoy-ui.yaml
templates/opsportal.yaml

chore: fix auth for landing and UI pages

---

templates/kommander.yaml
templates/konvoy-ui.yaml

Follow up to mesosphere/charts#58

Bump kommander chart version

---

templates/kommander.yaml

- As discussed, we will create the CR from the kubeaddons extra steps, we should not and will not do so here for now.

do not create kommander crd

---

templates/awsebscsiprovisioner.yaml

Fixes https://jira.mesosphere.com/browse/DCOS-56901

templates: bump awsebscsiprovisioner to v0.2.6

---

templates/dex-k8s-authenticator.yaml

related to the changes here: https://github.com/mesosphere/charts/pull/60

[dex-k8s-authenticator]: avoid using subPath for the secrets

---

templates/konvoy-ui.yaml

Add polling intervals used in kommander chart as env vars. Companion PR to mesosphere/charts#69

Add polling intervals for konvoy ui

---

templates/traefik-forward-auth.yaml

Depends on https://github.com/mesosphere/charts/pull/74

tfa: update to version with hooks

---

templates/kommander.yaml
templates/konvoy-ui.yaml

bumping latest chart version that should allow us to eliminate extra steps.

chart version bump for kommander

---

templates/kommander.yaml
templates/konvoy-ui.yaml

need to allow creation of crd.

[chore] allow the creation of the crd

---

templates/dex-k8s-authenticator.yaml

JIRA PR: https://jira.mesosphere.com/browse/DCOS-56408
dex-k8s-authenticator PR: https://github.com/mhrabovcin/dex-k8s-authenticator/pull/1

templates/dex-k8s-authenticator: bump container

---

templates/kibana.yaml

Fixed the spacing and corrected the service name used by the init container.

kibana: fix extraContainers

---

templates/opsportal.yaml

includes creation of secret used by other tools,
depends on https://github.com/mesosphere/charts/pull/81

[extrastep] opsportal use the right chart version

---

templates/kommander.yaml
templates/konvoy-ui.yaml

also use the default value for konvoy-ui addon

version bump kommander chart

---

templates/prometheus.yaml

grafana: fix CPUThrottlingHigh issues

---

templates/prometheus.yaml

https://prometheus.io/docs/introduction/overview/

Update prometheus docs link

---

templates/dex.yaml

JIRA: https://jira.mesosphere.com/browse/DCOS-56832
Theme PR: https://github.com/mesosphere/dex/pull/2

dex: bump dex container and set d2iq theme

---

templates/prometheus.yaml

Konvoy PR: https://github.com/mesosphere/konvoy/pull/665

Expose calico metrics

---

templates/dex-k8s-authenticator.yaml
templates/dex.yaml
templates/metallb.yaml
templates/opsportal.yaml
templates/traefik-forward-auth.yaml

Blocked by: https://github.com/mesosphere/charts/pull/97

Set resources for multiple addons

---

templates/velero.yaml

Blocked on https://github.com/mesosphere/charts/pull/99

bump velero chart

---

templates/opsportal.yaml
templates/prometheus.yaml

related to: https://github.com/mesosphere/charts/pull/98 and blocked by that PR https://github.com/mesosphere/charts/pull/98

templates: bump prometheus and opsportal

---

templates/velero.yaml

changes are here: https://github.com/mesosphere/charts/pull/109

bump velero chart version

---

templates/localvolumeprovisioner.yaml

Version 0.5.0 of 'localvolumeprovisioner' adds support for multiple
storage classes.

templates: bump 'localvolumeprovisioner'

---

templates/kommander.yaml

new version includes kubefed deployment

updated chart version of kommander

---

templates/cert-manager.yaml

Bump the version according to the changes in charts repo.

cert-manager: bump version

---

templates/konvoyconfig.yaml
templates/kube-oidc-proxy.yaml

Currently blocked on: https://github.com/mesosphere/charts/pull/143

Adds kube-oidc-proxy config

---

templates/dex.yaml
templates/traefik.yaml

Fix upgrade issue caused by hook resources

---

templates/traefik-forward-auth.yaml

Update to traefik-forward-auth 1.0.4

---

templates/dex.yaml
templates/traefik.yaml

The upgrade issue caused by hook resources.

Backport fixes for stable/1.15.4

---

templates/kommander.yaml

https://github.com/mesosphere/charts/pull/170

kommander version bump

---

templates/kommander.yaml
templates/opsportal.yaml

These were the changes we needed to make kommander work as expected, we are merging them back into master.

[kommander,opsportal] Kommander staging

---

templates/awsebscsiprovisioner.yaml
templates/cert-manager.yaml
templates/dashboard.yaml
templates/kommander.yaml
templates/localvolumeprovisioner.yaml
templates/nvidia.yaml
templates/velero.yaml

Reverts mesosphere/kubeaddons-configs#258

Revert "Remove namespace from spec on all addons"

---

templates/kommander.yaml
templates/opsportal.yaml

requires https://github.com/mesosphere/charts/pull/177

chore: bump opsportal and kommander to latest charts

---

templates/traefik.yaml

we bumped the version in the chart...

traefik: bump version

---

templates/gatekeeper.yaml

I can reproduce 100% of the times the reset issue if I install gatekeeper.

gatekeeper: temporary disable it

---

templates/kudo.yaml

tested with `konvoy up`. the controller deploys fine.
ran:
```
❯ kubectl kudo install kafka --instance=kafka
instance.kudo.dev/v1alpha1/kafka created
```
created the resources, however, `kafka` isn't running properly. I think that's out of scope.
for reference, this is what I got:
```
❯ kubectl describe pod kafka-kafka-0
Name:           kafka-kafka-0
Namespace:      default
Priority:       0
Node:           ip-10-0-131-128.us-west-2.compute.internal/10.0.131.128
Start Time:     Tue, 22 Oct 2019 13:03:45 -0400
Labels:         app=kafka
controller-revision-hash=kafka-kafka-bd9dfb9dd
heritage=kudo
kafka=kafka
kudo.dev/instance=kafka
kudo.dev/operator=kafka
statefulset.kubernetes.io/pod-name=kafka-kafka-0
Annotations:    cni.projectcalico.org/podIP: 192.168.122.215/32 …
```

add kudo addon

---

templates/dex.yaml

This includes the latest dex-controller 0.2.1.

dex: bump dex to 1.6.7

---

templates/kommander.yaml
templates/opsportal.yaml

Related to mesosphere/charts#253

chore: bump kommander and ops portal chart versions

---

templates/kibana.yaml
templates/prometheus.yaml

Bring in the changes from https://github.com/mesosphere/kubeaddons-configs/pull/297 to `master`.
Tested manually.

grafana/kibana: use a sidecar container for plugins

---

templates/dispatch.yaml

This currently points at my fork of the charts repo, please don't merge it yet.

dispatch: add initial kubeaddon

---

templates/kommander.yaml

Overrides needed so we can test with the betas.

feat(kommander): Update defaulting kubeaddons-configs values

---

templates/kommander.yaml
templates/opsportal.yaml

Depends on mesosphere/charts#267

chore: bump kommander/opsportal chart versions

---

templates/kommander.yaml

Testing latest changes in kcl to allow env variables to the webhook to pass HTTP_PROXY values.

kommander: bump kcl

---

templates/kommander.yaml
templates/opsportal.yaml

Depends on mesosphere/charts#276

chore: bump kommander/opsportal charts for new image tag 1.150.5

---

templates/kommander.yaml
templates/opsportal.yaml

Depends on mesosphere/charts#278

chore: bump kommander/opsportal charts for image update 1.150.12

---

templates/flagger.yaml

Add missing azure provider to flagger.

flagger: add azure provider

---

templates/dex.yaml
templates/dispatch.yaml
templates/elasticsearch.yaml
templates/elasticsearchexporter.yaml
templates/fluentbit.yaml
templates/konvoyconfig.yaml
templates/metallb.yaml
templates/traefik.yaml

I went through the list of addons and updated some outdated appversion annotations.

Update outdated appversion annotations

---

test/addons_test.go
test/go.mod
test/go.sum

Enable coverage of our elastic stack in CI.

[ci] Add elastic test coverage

---

templates/dashboard.yaml
templates/elasticsearch.yaml
templates/gatekeeper.yaml
templates/traefik.yaml

All these changes have been done by analyzing the resource usage on our soak cluster for this particular addons.

templates: addons adjust the resource limits

---

templates/kommander.yaml
templates/opsportal.yaml

⚠️ Depends on mesosphere/charts#293

chore: bump kommander/opsportal charts

---

templates/kommander.yaml

Depends on mesosphere/charts#296

chore: udpate kommander chart and version mapping

---

templates/dashboard.yaml
templates/opsportal.yaml
templates/traefik-forward-auth.yaml

Removes bearerproxy and adds dashboard ingress.

Dashboard authroization

---

templates/kommander.yaml

Depends on mesosphere/charts#300

chore: bump kommander chart

---

templates/prometheus.yaml

This PR is blocked by the chart PR with the respective changes

prometheus: kube-state-metrics

---

templates/dispatch.yaml

requires: mesosphere/charts#303 to merge in first

dispatch: update chart version

---

templates/kommander.yaml
templates/opsportal.yaml

⚠️ Depends on mesosphere/charts#311

chore: bump kommander and ops portal charts

---

templates/prometheus.yaml

https://jira.mesosphere.com/browse/DCOS-61841
https://jira.mesosphere.com/browse/DCOS-60484
This depends on https://github.com/mesosphere/charts/pull/309.
Corresponding kubernetes-base-addons PR: https://github.com/mesosphere/kubernetes-base-addons/pull/20
See the testing section in the description for https://github.com/mesosphere/charts/pull/309.

Upgrade prometheus-operator

---

templates/fluentbit.yaml

This was tested locally using an aws cluster.

[fluent-bit] update with audit log values.
